import {
  CheckCircle,
  AlertCircle,
  Clock,
  Loader2,
  Check,
  X,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  User,
  FileText,
  Settings,
  LogOut,
  Bell,
  Menu,
  Package,
  Home,
  ShoppingCart,
  Calendar,
  BarChart2,
  Tag,
  Trash,
  Edit,
  Map,
  Eye,
  RefreshCw,
  Upload,
  Download,
  Search,
  Filter,
  Plus,
  Minus,
} from 'lucide-react';

export const Icons = {
  spinner: Loader2,
  check: Check,
  close: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  creditCard: CreditCard,
  user: User,
  fileText: FileText,
  settings: Settings,
  logout: LogOut,
  notification: Bell,
  menu: Menu,
  package: Package,
  home: Home,
  cart: ShoppingCart,
  calendar: Calendar,
  chart: BarChart2,
  tag: Tag,
  delete: Trash,
  edit: Edit,
  location: Map,
  view: Eye,
  refresh: RefreshCw,
  upload: Upload,
  download: Download,
  search: Search,
  filter: Filter,
  add: Plus,
  remove: Minus,
  checkCircle: CheckCircle,
  alertCircle: AlertCircle,
  clock: Clock,
};